---
title: "Case Study 4: Election Prediction"
---

```{r, echo=FALSE, include=FALSE}
library(kableExtra)
library(knitr)
library(tidyverse)
```




# Learning Objectives

- continue developing skills in using models for prediction
- learn to scrape data from HTML pages and manipulate HTML elements in R
- evaluate and update predictions based on dynamic data
- combine data on a variety of levels (national, state, individual) to predict election outcomes

# Case Study Goals
Goals of this case study are (1) to predict whether the US House of Representatives remains in Republican control or reverts to Democratic control, and (2) to predict the outcomes of all NC Congressional elections

# Data

+ NC voter files at https://dl.ncsbe.gov/?prefix=data/ or somewhere related (Tessa to locate)
+ Cooperative Congressional Election Study https://cces.gov.harvard.edu/pages/welcome-cooperative-congressional-election-study 

# Reports

- Interim report 1: who votes in NC? Using the NC voter files, identify who votes in NC so that these data can be used with election surveys in order to predict outcomes of NC congressional elections. Present results in short in-class presentation.
- Interim report 2: in 5 pages (maximum), outline your models and general strategy for predicting the outcome of the 2018 elections.
- Final report: provide point and interval estimates of the % of votes won by each NC Congressional candidate, predicting the winner of each race. Provide point and interval estimates of the probability that the US House of Representatives remains under Republican control after the 2018 election.


# Resources

+ http://thisisstatistics.org/demystifying-the-election-prediction-2016-contest/ 
+ Why do we care about likely voters?  https://fivethirtyeight.com/features/registered-voter-polls-will-usually-overrate-democrats/ 
+ FiveThirtyEight's 2016 forecast details: https://fivethirtyeight.com/features/a-users-guide-to-fivethirtyeights-2016-general-election-forecast/ 
+ Potentially helpful blog 1: https://www.r-statistics.com/2016/08/presidential-election-predictions-2016/
+ Potentially helpful blog 2: https://github.com/hardin47/prediction2016/blob/master/predblog.pdf

# Slides


[Basics of Election Prediction: Tessa to do based on https://www.nytimes.com/2016/10/05/learning/lesson-plans/and-the-winner-is-predicting-the-2016-presidential-election.html](decks/cs04_1_deck.html)

[Mr. P Tutorial: Tessa based on http://www.princeton.edu/~jkastell/mrp_primer.html](decks/cs04_2_deck.html)






